### ISSUE TITLE
Add frontend linters in the pre-commit hook

### ISSUE THREAD

**Issue by neelansh27** [TeamCodeArena/DeliverEase#110]
Add htmlhint for HTML and stylelint for CSS linting in the pre-commit hook.

Ref:
https://htmlhint.com/docs/user-guide/getting-started
https://stylelint.io/user-guide/get-started/

**Comment by neelansh27** [comment]
@SID262000 please assign this issue to me.

**Comment by Atrika10** [comment]
@neelansh27, may I suggest renaming the issue to 'Add Frontend Linter in the Pre-commit Hook'? This change will help avoid any confusion among contributors who might wonder about the purpose of this issue since we already have a frontend linter in place.
Your consideration is much appreciated. 
Thank you
 Atrika

**Comment by Devansh-Singh-Parmar** [comment]
I totally agree with @Atrika10 

cc @SID262000 @neelansh27

**Comment by neelansh27** [comment]
@Atrika10 I thought about it too but to keep the title short, I mentioned about the pre-commit hook in the comment instead. 
It's ok, I will add it in the title as well.

**Comment by neelansh27** [comment]
This issue was resolved in #115
