### ISSUE TITLE
Add End to End Testing of the website on Browser with Selenium 

### ISSUE THREAD

**Issue by AryanGupta0007** [TeamCodeArena/DeliverEase#79]
https://selenium-python.readthedocs.io/index.html

**Comment by neelansh27** [comment]
I would like to do testing for the seller and main app @AryanGupta0007

**Comment by Devansh-Singh-Parmar** [comment]
I can do testing of frontend, both.(if that's required)
cc: @AryanGupta0007

**Comment by AryanGupta0007** [comment]
@Devansh-Singh-Parmar this issue is related to Python.  Frontend testing is a separate issue.

**Comment by Devansh-Singh-Parmar** [comment]
Got it!

**Comment by SID262000** [comment]
Just to make sure we all are on the same page, do we have Java code in our codebase since you folks decided to use Selenium. Also, I wouldn't recommend getting started with the end to end testing unless we have the unit test cases in-place for the entire codebase followed by the integration testing.
cc: @AryanGupta0007 @neelansh27

**Comment by AryanGupta0007** [comment]
Selenium is available in Python also
@SID262000

**Comment by SID262000** [comment]
Go ahead with Selenium implementation. Thanks
cc: @AryanGupta0007 @neelansh27
